//LOCALHOST 
//Get all GET http://localhost:3000/cats ###

//Get single by ID GET http://localhost:3000/cats/62896d4c7ec89f1cfee36375 ###

//Add in JSON POST http://localhost:3000/cats HTTP/1.1 Content-Type: application/json

{
"breed":"Siamese", "color":"tan & black", "weight":"10 lbs"
}

###





